#!/usr/bin/env python3
"""Translate the project README into one or more target languages.

Uses any OpenAI-compatible Chat Completions API. All configuration comes from
environment variables; see .github/workflows/translate-readme.yml for details.
No third-party dependencies are required (standard library only).
"""

import json
import os
import sys
import time
import urllib.error
import urllib.request


def env(name, default=""):
    """Return a non-empty trimmed env value, or the default."""
    value = os.environ.get(name, "")
    return value.strip() or default


API_BASE = env("LLM_API_BASE", "https://api.openai.com/v1")
API_KEY = os.environ.get("LLM_API_KEY", "").strip()
MODEL = env("LLM_MODEL", "gpt-4o-mini")
SOURCE_FILE = env("SOURCE_FILE", "README.md")
SOURCE_LANGUAGE = env("SOURCE_LANGUAGE", "Chinese")
TARGET_LANGUAGES = env("TARGET_LANGUAGES", "en:English")
TIMEOUT = int(env("LLM_TIMEOUT", "120"))


def parse_languages(spec):
    """Parse 'en:English,ja:日本語' into [('en', 'English'), ('ja', '日本語')]."""
    result = []
    for item in spec.split(","):
        item = item.strip()
        if not item or ":" not in item:
            continue
        code, name = item.split(":", 1)
        code = code.strip()
        name = name.strip()
        if code and name:
            result.append((code, name))
    return result


def call_api(system_prompt, user_prompt, retries=2):
    """Call the OpenAI-compatible chat completions endpoint with retries."""
    url = API_BASE.rstrip("/") + "/chat/completions"
    payload = {
        "model": MODEL,
        "temperature": 0.2,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    }
    data = json.dumps(payload).encode("utf-8")
    last_error = None
    for attempt in range(retries + 1):
        request = urllib.request.Request(
            url,
            data=data,
            headers={
                "Authorization": "Bearer " + API_KEY,
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
                body = json.loads(response.read().decode("utf-8"))
                return body["choices"][0]["message"]["content"].strip()
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            last_error = "{} {} - {}".format(exc.code, exc.reason, detail)
        except Exception as exc:  # noqa: BLE001
            last_error = str(exc)
        if attempt < retries:
            time.sleep(2 ** attempt)
    raise RuntimeError("LLM request failed after retries: " + str(last_error))


SYSTEM_PROMPT = (
    "You are a professional technical translator for software documentation. "
    "You translate Markdown precisely and idiomatically while keeping all "
    "structure, links, code, and formatting intact."
)


def build_user_prompt(source_text, source_language, target_language):
    """Build the translation prompt for a single target language."""
    return (
        "Translate the Markdown document inside <source-document> from {src} "
        "into {tgt}. Follow these rules strictly:\n"
        "1. Output ONLY the translated Markdown. No preamble, no explanation, "
        "and do NOT wrap the whole output in a code fence.\n"
        "2. Preserve ALL Markdown structure exactly: headings, lists, tables, "
        "blockquotes, horizontal rules, HTML tags, and any YAML front matter "
        "(translate the values but keep the --- delimiters and keys).\n"
        "3. Never translate the contents of fenced code blocks or inline code.\n"
        "4. Keep all URLs, file paths, shell commands, and the product name "
        '"Vimo" unchanged.\n'
        "5. Translate natural-language prose so it reads naturally to a native "
        "{tgt} reader.\n"
        "6. Keep any emoji exactly as they appear.\n\n"
        "<source-document>\n{src_text}\n</source-document>"
    ).format(src=source_language, tgt=target_language, src_text=source_text)


AUTO_HEADER = (
    "<!-- Auto-generated by .github/workflows/translate-readme.yml. "
    "Do not edit this file manually; edit README.md instead. -->\n\n"
)


def main():
    if not API_KEY:
        print("ERROR: LLM_API_KEY is not set.", file=sys.stderr)
        return 1

    if not os.path.exists(SOURCE_FILE):
        print("ERROR: source file not found: " + SOURCE_FILE, file=sys.stderr)
        return 1

    with open(SOURCE_FILE, "r", encoding="utf-8") as handle:
        source_text = handle.read()

    languages = parse_languages(TARGET_LANGUAGES)
    if not languages:
        print("ERROR: no target languages parsed from: " + TARGET_LANGUAGES, file=sys.stderr)
        return 1

    print("Translating {} ({} chars) -> {}".format(
        SOURCE_FILE, len(source_text), ", ".join(name for _, name in languages)))
    print("Provider: {} | model: {}".format(API_BASE, MODEL))

    failures = 0
    for code, name in languages:
        output_file = "README_{}.md".format(code.upper())
        print("\n--- {} ({}) -> {} ---".format(code, name, output_file))
        try:
            translated = call_api(
                SYSTEM_PROMPT,
                build_user_prompt(source_text, SOURCE_LANGUAGE, name),
            )
        except Exception as exc:  # noqa: BLE001
            print("FAILED: " + str(exc), file=sys.stderr)
            failures += 1
            continue

        with open(output_file, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(AUTO_HEADER + translated.rstrip() + "\n")
        print("OK ({} chars)".format(len(translated)))

    if failures:
        print("\n{} translation(s) failed.".format(failures), file=sys.stderr)
    else:
        print("\nAll translations completed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
